#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cnpg-postgresql.fullname" . }}
  labels:
    {{- include "cnpg-postgresql.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.replicaCount }}
  imageName: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  storage:
    size: {{ .Values.storage.size }}
    storageClass: {{ .Values.storage.class | quote }}
  managed:
    roles:
      {{- range $db := .Values.databases }}
      - name: {{ $db.owner.username }}
        ensure: present
        login: true
        passwordSecret:
          name: {{ default (printf "%s-owner-secret" $db.owner.username) $db.owner.passwordSecret }}
      {{- end }}
