# Default values for cloudnative-pg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/cloudnative-pg/postgresql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "17.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

storage:
  size: 2Gi
  class: standard

# Create the following databases
databases: []
#  - name: hive-metastore
#    owner:
#      username: "hms"
#      passwordSecret: hms-db-credentials
#    schemas: []
#  - name: superset
#    owner:
#      username: superset
#      password: superset
#    schemas:
#    - main

job:
  ttlSecondsAfterFinished: 60
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
