nameOverride: ""
fullnameOverride: ""

username: admin
password: admin123
auth_secret: auth-user-secret
s3_secret: creds-s3-secret
sourceS3Secrets:
  - name: creds-example-s3
    actions:
      - Admin
      - Read
      - Write

  - name: creds-example-s3-2
    actions:
      - Read
